TYPE=VIEW
query=select straight_join `pp`.`QTD_NECESSARIA` AS `QTD_NECESSARIA`,`pp`.`TXT_OBSERVACAO` AS `TXT_OBSERVACAO`,`l`.`DSC_LOJA` AS `DSC_LOJA`,`l`.`DSC_LOJA_ABREVIADO` AS `DSC_LOJA_ABREVIADO`,`l`.`COD_LOJA` AS `COD_LOJA`,`pr`.`DSC_PRODUTO` AS `DSC_PRODUTO`,`p`.`IND_FECHADO` AS `IND_FECHADO`,`p`.`DATA_ENTREGA_PREVISTA` AS `DATA_ENTREGA_PREVISTA`,`p`.`COD_PERIODO_DIA` AS `COD_PERIODO_DIA`,`l`.`COD_CLIENTE` AS `COD_CLIENTE`,`d`.`COD_DEPARTAMENTO` AS `COD_DEPARTAMENTO`,`c`.`COD_CLASSIFICACAO` AS `COD_CLASSIFICACAO`,`d`.`DSC_DEPARTAMENTO` AS `DSC_DEPARTAMENTO`,`c`.`DSC_CLASSIFICACAO` AS `DSC_CLASSIFICACAO` from (((((`capa`.`re_pedido` `p` join `capa`.`re_pedido_produto` `pp` on(((`p`.`COD_PEDIDO` = `pp`.`COD_PEDIDO`) and (year(`p`.`DATA_PEDIDO`) = year(now()))))) join `capa`.`en_produto` `pr` on((`pp`.`COD_PRODUTO` = `pr`.`COD_PRODUTO`))) join `capa`.`en_classificacao` `c` on((`pr`.`COD_CLASSIFICACAO` = `c`.`COD_CLASSIFICACAO`))) join `capa`.`en_loja` `l` on((`p`.`COD_LOJA` = `l`.`COD_LOJA`))) join `capa`.`en_departamento` `d` on((`c`.`COD_DEPARTAMENTO` = `d`.`COD_DEPARTAMENTO`)))
md5=81caf205f0ee3e869246c20a26e3e9c4
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2015-09-17 19:04:33
create-version=1
source=SELECT STRAIGHT_JOIN `pp`.`qtd_necessaria`       AS `QTD_NECESSARIA`,\n       `pp`.`txt_observacao`       AS `TXT_OBSERVACAO`,   \n       `l`.`dsc_loja`              AS `DSC_LOJA`, \n       `l`.`dsc_loja_abreviado`  AS `DSC_LOJA_ABREVIADO`, \n       `l`.`cod_loja`              AS `COD_LOJA`, \n       `pr`.`dsc_produto`          AS `DSC_PRODUTO`, \n       `p`.`ind_fechado`           AS `IND_FECHADO`, \n       `p`.`data_entrega_prevista` AS `DATA_ENTREGA_PREVISTA`, \n       `p`.`cod_periodo_dia`       AS `COD_PERIODO_DIA`, \n       `l`.`cod_cliente`           AS `COD_CLIENTE`, \n       `d`.`cod_departamento`      AS `COD_DEPARTAMENTO`, \n       `c`.`cod_classificacao`     AS `COD_CLASSIFICACAO`, \n       `d`.`dsc_departamento`      AS `DSC_DEPARTAMENTO`, \n       `c`.`dsc_classificacao`     AS `DSC_CLASSIFICACAO` \nFROM   `re_pedido` `P` \nINNER JOIN `re_pedido_produto` `PP` \n   ON `p`.`cod_pedido` = `pp`.`cod_pedido`\n  AND YEAR(P.DATA_PEDIDO) = YEAR(NOW())\nINNER JOIN `en_produto` `PR` \n   ON `pp`.`cod_produto` = `pr`.`cod_produto` \nINNER JOIN `en_classificacao` `C` \n   ON `pr`.`cod_classificacao` = `c`.`cod_classificacao`\nINNER JOIN `en_loja` `L` \n   ON `p`.`cod_loja` = `l`.`cod_loja`\nINNER JOIN `en_departamento` `D` \n   ON `c`.`cod_departamento` = `d`.`cod_departamento`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select straight_join `pp`.`QTD_NECESSARIA` AS `QTD_NECESSARIA`,`pp`.`TXT_OBSERVACAO` AS `TXT_OBSERVACAO`,`l`.`DSC_LOJA` AS `DSC_LOJA`,`l`.`DSC_LOJA_ABREVIADO` AS `DSC_LOJA_ABREVIADO`,`l`.`COD_LOJA` AS `COD_LOJA`,`pr`.`DSC_PRODUTO` AS `DSC_PRODUTO`,`p`.`IND_FECHADO` AS `IND_FECHADO`,`p`.`DATA_ENTREGA_PREVISTA` AS `DATA_ENTREGA_PREVISTA`,`p`.`COD_PERIODO_DIA` AS `COD_PERIODO_DIA`,`l`.`COD_CLIENTE` AS `COD_CLIENTE`,`d`.`COD_DEPARTAMENTO` AS `COD_DEPARTAMENTO`,`c`.`COD_CLASSIFICACAO` AS `COD_CLASSIFICACAO`,`d`.`DSC_DEPARTAMENTO` AS `DSC_DEPARTAMENTO`,`c`.`DSC_CLASSIFICACAO` AS `DSC_CLASSIFICACAO` from (((((`capa`.`re_pedido` `p` join `capa`.`re_pedido_produto` `pp` on(((`p`.`COD_PEDIDO` = `pp`.`COD_PEDIDO`) and (year(`p`.`DATA_PEDIDO`) = year(now()))))) join `capa`.`en_produto` `pr` on((`pp`.`COD_PRODUTO` = `pr`.`COD_PRODUTO`))) join `capa`.`en_classificacao` `c` on((`pr`.`COD_CLASSIFICACAO` = `c`.`COD_CLASSIFICACAO`))) join `capa`.`en_loja` `l` on((`p`.`COD_LOJA` = `l`.`COD_LOJA`))) join `capa`.`en_departamento` `d` on((`c`.`COD_DEPARTAMENTO` = `d`.`COD_DEPARTAMENTO`)))
