TYPE=VIEW
query=select `pp`.`TXT_OBSERVACAO` AS `TXT_OBSERVACAO`,`pp`.`QTD_NECESSARIA` AS `QTD_NECESSARIA`,`l`.`DSC_LOJA` AS `DSC_LOJA`,`l`.`COD_LOJA` AS `COD_LOJA`,`prod`.`DSC_PRODUTO` AS `DSC_PRODUTO`,`p`.`IND_FECHADO` AS `IND_FECHADO`,`p`.`DATA_ENTREGA_PREVISTA` AS `DATA_ENTREGA_PREVISTA`,`p`.`COD_PERIODO_DIA` AS `COD_PERIODO_DIA`,`l`.`COD_CLIENTE` AS `COD_CLIENTE`,`d`.`COD_DEPARTAMENTO` AS `COD_DEPARTAMENTO`,`c`.`COD_CLASSIFICACAO` AS `COD_CLASSIFICACAO`,`d`.`DSC_DEPARTAMENTO` AS `DSC_DEPARTAMENTO`,`c`.`DSC_CLASSIFICACAO` AS `DSC_CLASSIFICACAO` from ((((((`cpa`.`re_pedido` `p` join `cpa`.`re_pedido_produto` `pp` on((`p`.`COD_PEDIDO` = `pp`.`COD_PEDIDO`))) join `cpa`.`en_produto` `prod` on((`pp`.`COD_PRODUTO` = `prod`.`COD_PRODUTO`))) join `cpa`.`re_classificacao_produto` `pr` on((`pp`.`COD_PRODUTO` = `pr`.`COD_PRODUTO`))) join `cpa`.`en_classificacao` `c` on((`pr`.`COD_CLASSIFICACAO` = `c`.`COD_CLASSIFICACAO`))) join `cpa`.`en_loja` `l` on((`p`.`COD_LOJA` = `l`.`COD_LOJA`))) left join `cpa`.`en_departamento` `d` on((`c`.`COD_DEPARTAMENTO` = `d`.`COD_DEPARTAMENTO`)))
md5=fce21a15e2a6ded33ead19dc25aac0f4
updatable=0
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2015-07-06 12:31:01
create-version=1
source=select `pp`.`TXT_OBSERVACAO` AS `TXT_OBSERVACAO`,`pp`.`QTD_NECESSARIA` AS `QTD_NECESSARIA`,`l`.`DSC_LOJA` AS `DSC_LOJA`,`l`.`COD_LOJA` AS `COD_LOJA`,`prod`.`DSC_PRODUTO` AS `DSC_PRODUTO`,`p`.`IND_FECHADO` AS `IND_FECHADO`,`p`.`DATA_ENTREGA_PREVISTA` AS `DATA_ENTREGA_PREVISTA`,`p`.`COD_PERIODO_DIA` AS `COD_PERIODO_DIA`,`l`.`COD_CLIENTE` AS `COD_CLIENTE`,`d`.`COD_DEPARTAMENTO` AS `COD_DEPARTAMENTO`,`c`.`COD_CLASSIFICACAO` AS `COD_CLASSIFICACAO`,`d`.`DSC_DEPARTAMENTO` AS `DSC_DEPARTAMENTO`,`c`.`DSC_CLASSIFICACAO` AS `DSC_CLASSIFICACAO` from ((((((`re_pedido` `P` join `re_pedido_produto` `PP` on((`p`.`COD_PEDIDO` = `pp`.`COD_PEDIDO`))) join `en_produto` `PROD` on((`pp`.`COD_PRODUTO` = `prod`.`COD_PRODUTO`))) join `re_classificacao_produto` `PR` on((`pp`.`COD_PRODUTO` = `pr`.`COD_PRODUTO`))) join `en_classificacao` `C` on((`pr`.`COD_CLASSIFICACAO` = `c`.`COD_CLASSIFICACAO`))) join `en_loja` `L` on((`p`.`COD_LOJA` = `l`.`COD_LOJA`))) left join `en_departamento` `D` on((`c`.`COD_DEPARTAMENTO` = `d`.`COD_DEPARTAMENTO`)))
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `pp`.`TXT_OBSERVACAO` AS `TXT_OBSERVACAO`,`pp`.`QTD_NECESSARIA` AS `QTD_NECESSARIA`,`l`.`DSC_LOJA` AS `DSC_LOJA`,`l`.`COD_LOJA` AS `COD_LOJA`,`prod`.`DSC_PRODUTO` AS `DSC_PRODUTO`,`p`.`IND_FECHADO` AS `IND_FECHADO`,`p`.`DATA_ENTREGA_PREVISTA` AS `DATA_ENTREGA_PREVISTA`,`p`.`COD_PERIODO_DIA` AS `COD_PERIODO_DIA`,`l`.`COD_CLIENTE` AS `COD_CLIENTE`,`d`.`COD_DEPARTAMENTO` AS `COD_DEPARTAMENTO`,`c`.`COD_CLASSIFICACAO` AS `COD_CLASSIFICACAO`,`d`.`DSC_DEPARTAMENTO` AS `DSC_DEPARTAMENTO`,`c`.`DSC_CLASSIFICACAO` AS `DSC_CLASSIFICACAO` from ((((((`cpa`.`re_pedido` `p` join `cpa`.`re_pedido_produto` `pp` on((`p`.`COD_PEDIDO` = `pp`.`COD_PEDIDO`))) join `cpa`.`en_produto` `prod` on((`pp`.`COD_PRODUTO` = `prod`.`COD_PRODUTO`))) join `cpa`.`re_classificacao_produto` `pr` on((`pp`.`COD_PRODUTO` = `pr`.`COD_PRODUTO`))) join `cpa`.`en_classificacao` `c` on((`pr`.`COD_CLASSIFICACAO` = `c`.`COD_CLASSIFICACAO`))) join `cpa`.`en_loja` `l` on((`p`.`COD_LOJA` = `l`.`COD_LOJA`))) left join `cpa`.`en_departamento` `d` on((`c`.`COD_DEPARTAMENTO` = `d`.`COD_DEPARTAMENTO`)))
